import React from 'react';
import {useTranslation} from "@/utils/useTranslation";
import Image from "next/image";
import {useDateFormatter} from "@/utils/useDateFormatter";
import withAuth from "@/hoc/withAuth";

const Test: React.FC = () => {
    const text = useTranslation();
    const dateFormat = useDateFormatter();
    const contentList = [
        'Complete',
        'Finalize',
        'Prepare',
        'Make',
        'Handle',
        "Create"
    ];

    const recipientList = [
        'John Doe (Finance Department)',
        'Jane Smith (Marketing Team)',
        'Samuel Green (Executive Team)'
    ];

    return (
        <div className="bg-gray-700 min-h-screen py-10">
            <div className="w-96 mx-auto bg-white p-4 shadow-lg rounded-lg">
                <div className="flex flex-row items-center justify-center">
                    <Image src="/default.png" alt="Kop Surat" className="w-[100px] h-auto mb-4" width={200}
                           height={200}/>
                </div>
                <hr className="border border-gray-700"/>
                <p className="font-bold text-blue-800 text-center text-lg">{text('status')}</p>
                <hr className="border border-gray-700 mb-2"/>
                <table className="w-full mb-2">
                    <tbody>
                    <tr>
                        <td className="text-xs font-bold">{text('letter_number')}</td>
                        <td className="text-xs text-left">:</td>
                        <td className="text-xs text-left">SM?WAOJW</td>
                    </tr>
                    <tr>
                        <td className="text-xs font-bold">{text('date')}</td>
                        <td className="text-xs text-left">:</td>
                        <td className="text-xs text-left">{dateFormat('2024/1/2')}</td>
                    </tr>
                    <tr>
                        <td className="text-xs font-bold">{text('disposition_creator')}</td>
                        <td className="text-xs text-left">:</td>
                        <td className="text-xs text-left">name</td>
                    </tr>
                    </tbody>
                </table>
                <hr className="border border-gray-700 mb-2"/>
                <div className="mb-4">
                    <p className="font-bold text-xs mb-2">{text('disposition_content')}:</p>
                    <ul className="grid grid-cols-3 text-xs">
                        {contentList.map((item, index) => (
                            <li key={index}>{item}</li>
                        ))}
                    </ul>
                </div>
                <div className="mb-4">
                    <p className="font-bold text-xs mb-2">{text('recipient')}:</p>
                    <div className="flex flex-wrap gap-2">
                        {recipientList.map((recipient, index) => (
                            <span key={index} className="bg-gray-200 text-xs py-1 px-2 rounded-lg">{recipient}</span>
                        ))}
                    </div>
                </div>
                <div className="mb-4">
                    <p className="font-bold text-xs mb-2">{text('note')}:</p>
                    <p className="text-xs">note</p>
                </div>
                <div className="flex justify-end mt-6">
                    <Image src="/qrExample.png" alt="QR Code" className="h-[80px] w-auto" width={200} height={200}/>
                </div>
                <div className="text-center mt-6 text-xs">
                    <p className="text-xs">Generated by SPARTI</p>
                </div>
            </div>
        </div>
    );
};

export default withAuth(Test, ['Administrator']);
