import { DetailLetterIn, Disposisi, DisposisiLevel2, DisposisiLevel3 } from "@/interfaces/LetterIn";
import { useTranslation } from "@/utils/useTranslation";

export const useGenerateDispositionHTML = () => {
    const text = useTranslation();
    return (
        letter: DetailLetterIn,
        disposition: Disposisi | DisposisiLevel2 | DisposisiLevel3,
        status: string,
        qrCodeUrl: string,
        date: string,
        kopSuratUrl: string
    ): string => {
        return `
      <div style="font-family: Arial, sans-serif; padding: 20px; width: 100%; font-size: 10px;">
          <div style="text-align: center; margin-bottom: 10px;">
              <img src="${kopSuratUrl}" alt="Kop Surat" style="max-height: 60px; width: auto;"/>
          </div>
          <hr style="border: 1px solid black; margin-bottom: 10px;" />
          <span style="font-weight: bold; color: #007bff; font-size: 14px;">${text(status)}</span>
          <div style="display: flex; justify-content: space-between; margin-top: 10px; margin-bottom: 10px; border-bottom: 1px solid black;">
              <div>
                  <div style="margin-bottom: 5px;">
                      <label style="font-weight: bold; font-size: 12px;">${text('letter_number')}:</label>
                      <div style="font-size: 10px;">${letter.nomor_surat}</div>
                  </div>
                  <div style="margin-bottom: 10px;">
                      <label style="font-weight: bold; font-size: 12px;">${text('date')}:</label>
                      <div style="font-size: 10px;">${date}</div>
                  </div>
              </div>
              <div style="text-align: right;">
                  <label style="font-weight: bold; font-size: 12px;">${text('disposition_creator')}:</label>
                  <div style="font-size: 10px;">${disposition.creator.name}</div>
              </div>
          </div>
          <div style="margin-bottom: 10px;">
              <label style="font-weight: bold; font-size: 12px;">${text('disposition_content')}:</label>
              <div style="font-size: 10px;">${disposition.isi_disposisis.map((isi) => isi.isi).join(", ")}</div>
          </div>
          <div style="margin-bottom: 10px;">
              <label style="font-weight: bold; font-size: 12px; margin-bottom: 5px;">${text('recipient')}:</label>
              <div style="display: flex; flex-wrap: wrap; gap: 5px; font-size: 10px; margin-top: 5px; padding-top: 10px">
                  ${disposition.log_disposisis.map((log) => `
                      <span style="background: #f0f0f0; padding: 0 5px 10px; border-radius: 5px;">
                          ${log.penerima_user.name} (${log.penerima_user.role})
                      </span>
                  `).join("")}
              </div>
          </div>
          <div style="margin-bottom: 10px;">
              <label style="font-weight: bold; font-size: 12px;">${text('note')}:</label>
              <div style="font-size: 10px;">${disposition.catatan}</div>
          </div>
          <div style="display: flex; justify-content: flex-end; margin-top: 30px;">
              <img src="${qrCodeUrl}" alt="QR Code" style="height: 80px; width: auto;"/>
          </div>
          <div style="text-align: center; margin-top: 20px; font-size: 10px;">
              <p>Generated by SPARTI: <a href="https://sparti.online" target="_blank">sparti.online</a></p>
          </div>
      </div>
    `;
    };
};
